# Generated by Django 2.1.2 on 2018-10-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=15)),
                ('edad', models.IntegerField(max_length=2)),
                ('sangre', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='accidente',
            name='personas',
            field=models.ManyToManyField(to='accidentes.Persona'),
        ),
    ]
