# Generated by Django 2.1.2 on 2018-10-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0002_auto_20181030_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidente',
            name='latitud',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accidente',
            name='longitud',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
